### PR TITLE
thevoid: library-wide signal handling mechanics reworked

### PR DESCRIPTION
**Pull request by shindo**
All signal handling mechanics moved to thevoid::signal_handler namespace.

[sigaction](http://man7.org/linux/man-pages/man2/sigaction.2.html) function is used to register handlers for specific signals. This function changes signal's disposition process-wide.
Registered signal handlers just set corresponding atomic flags which are monitored by separate thread ("void_signal").

Disadvantages of other approaches:
- signal:
  "The effects of [signal()](http://man7.org/linux/man-pages/man2/signal.2.html) in a multithreaded process are unspecified."
- signalfd:
  [signalfd()](http://man7.org/linux/man-pages/man2/signalfd.2.html) creates file descriptor that can be monitored for queued signals (blocked for the entire thread group). Thus, it's required to register (and block) all necessary signals from the main thread before creating any other threads. Otherwise, created threads may have these signals as not blocked and will receive them with default disposition.

Added functions to add/remove server to/from global signal handling:
thevoid::signal_handler::add_server(base_server\*)
thevoid::signal_handler::remove_server(base_server\*)

Pointers to all added servers are stored within global set and received signals affect all of them.
On server's destruction its pointer will be removed from the set, but it's still possible to remove server's pointer from the set if one doesn't want their server to react on specified signals.

Added functions to register stop/reload signals:
thevoid::signal_handler::register_stop(int signal)
thevoid::signal_handler::register_reload(int signal)

Added functions to start/stop library-wide signal handling mechanics:
thevoid::signal_handler::start()
thevoid::signal_handler::stop()

On start() separate thread ("void_signal") will be created and it'll run until stop() is called.

### CODE REVIEW

**Comment by bioothod** [comment]
Is there any way not to register new thread just for signal handling?
Can it be done by IO threads or in caller's context?

**Comment by shindo** [comment]
Are there any serious concerns about separate thread?

Implemented signal handling mechanics is "additional" feature (see it as helper), enabling it is user's decision. Thus, this cost looks acceptable.

IO threads are not about this and should not take part here. About caller's context -- I don't get it.

Moreover I think that library should not handle signals and leave this task for user (because this topic looks really hard due to lots of use cases).

File: thevoid/signal_handler.cpp [hunk 1]
```diff
@@ -0,0 +1,139 @@
+#include "server.hpp"
+
+#include <mutex>
+#include <set>
+#include <thread>
+#include <atomic>
```
Comment (iderikon) [inline thevoid/signal_handler.cpp]: It does not compile with gcc 4.4. You should include either atomic or cstdatomic header depends on compiler.

File: thevoid/signal_handler.cpp [hunk 2]
```diff
@@ -0,0 +1,139 @@
...
+		}
+		else if (reload_request != -1) {
+			int signal_value = reload_request;
+
+			reload_request = -1;
+
+			handle_reload(signal_value);
+		}
+		else {
+			std::this_thread::sleep_for(std::chrono::seconds(1));
```
Comment (iderikon) [inline thevoid/signal_handler.cpp]: It does not compile with gcc 4.4. The method sleep_for does not implemented there.

File: thevoid/signal_handler.cpp (hunk 1 above)
Comment (shindo) [inline thevoid/signal_handler.cpp]: Fixed.

File: thevoid/signal_handler.cpp [hunk 3]
```diff
@@ -0,0 +1,139 @@
...
+	running = true;
+	monitoring_thread = std::thread(run);
+}
+
+void stop() {
+	running = false;
+
+	if (monitoring_thread.joinable()) {
+		monitoring_thread.join();
+	}
```
Comment (iderikon) [inline thevoid/signal_handler.cpp]: The variable running should be set to false when thread was joined to prevent processing the method start before thread is joined.

**Comment by bioothod** [comment]
swarm and thevoid are not general purpose libraries, it is not really possible to implement correct termination handler without knowledge of the underlying system. Client has to integrate own signal handler and library's one - this is not a feasible task, basically only library's signal handler is always used.
There is no documentation and examples of how to integrate library's signal handlers into client's code.

Using additional thread for every new kind of tasks is a waste of resources. It is not *very* heavy and doesn't somehow limit performance, but it is a resource waste, it is a non-optimal design. IO threads perfectly suit for this kind of tasks since we have to create them, this is required for system to operate, and after all - signal handling is just another *task* for threads to complete, no matter whether it is socket read or server tear down.

I could get additional signal thread requirement if there would be no possibility to stop server (or perform any other *signal* tasks) from inside its own IO threads, but it doesn't look like it is the case. Please reconsider additional thread creation logic in favor of assigning this task to IO thread. If it is not possible, I will apply your patch, but then it requires example how to integrate this new logic into client code (who creates the thread, how to mix client's handler and library's one and so on).

File: thevoid/signal_handler.cpp (hunk 2 above)
Comment (shindo) [inline thevoid/signal_handler.cpp]: _GLIBCXX_USE_NANOSLEEP define added.
You can read about it here: http://stackoverflow.com/questions/4438084/stdthis-threadsleep-for-and-gcc

**Comment by shindo** [comment]
Everything is possible, I just don't want to do it.

From my point of view it would be better to do not provide library's signal handling mechanics. But such mechanics is presented already, so we still need to provide it.

There's nothing special with proposed signal handling implementation, and it could be fully implemented client-side.

About documentation and example -- `run_server()` function:
```cpp
template <typename Server, typename... Args>
int run_server(int argc, char **argv, Args &&...args)
{
	signal_handler::start();

	signal_handler::register_stop(SIGINT);
	signal_handler::register_stop(SIGTERM);
	signal_handler::register_stop(SIGALRM);
	signal_handler::register_reload(SIGHUP);

	auto server = create_server<Server>(std::forward<Args>(args)...);
	signal_handler::add_server(server.get());

	int ret_code = server->run(argc, argv);

	signal_handler::stop();
	signal_handler::remove_server(server.get());

	return ret_code;
}
```

With `thevoid::signal_handler::start()` function one starts signal handling separate thread.
With `thevoid::signal_handler::register_stop()` and `thevoid::signal_handler::register_reload()` functions one registers signals for stop and reload actions (`sigaction()` function is used to register action on specified signal).
With `thevoid::signal_handler::add_server()` function one adds pointer to their server to global set of servers that will react on received signals (either stop or reload).
With `thevoid::signal_handler::remove_server()` function one removes pointer to their server from global set of servers.
Finally, with `thevoid::signal_handler::stop()` function one stops separate signal handling thread.

On server's destruction its pointer will be removed from global set of servers. It's been done to not require user to remove their servers "manually". Probably it should be removed (signal-related action within server's destructor) to completely separate signal handling mechanics and server's internal logic (with its IO threads and so on).

**Comment by bioothod** [comment]
This code example exactly says why it is not a library at all, but framework. How could one setup *own* SIGTERM handler which will be used with the library's one? It is not possible.
The only possible task is **not** to register some non obligatory handler (like SIGHUP handler). Also, why in the hell would I want to stop server on alarm?

By 'caller's' context above I talked about context where `->run()` is executed.

I recommend hiding all that code somewhere inside `create_server()`, since it is all unneeded magic for request processing itself. Also, code example should be not some function in source code, but real example code one could use as a reference - cmake, separate file (or directory), a lot of comments describing why it is needed and how it can be used.

**Comment by shindo** [comment]
These signals (SIGALRM, SIGALRM, etc.) were used earlier

**Comment by shindo** [comment]
These signals (SIGALRM, SIGALRM, etc.) were used earlier this way, so let's do not break previous behaviour. 

I would recommend user to not use run_server() function, instead create server with create_server(), register their own handlers for signals with whatever method they want and handle signals appropriately (e.g. stop or reload server's configuration).

Once again, I don't want to add signal handling mechanics into server's logic. It should be user's decision to handle (and how) signals or not.
This pull request implements signal handling as "additional" feature, if one wants they can use it, but we don't limit them with it. 

All this stuff about documentation sounds really great (but it looks like overkill, don't you think?), but the current task is not about that.

**Comment by bioothod** [comment]
If I create my own SIGTERM handler server will explode, since I do not know how to run `stop_request.store(sig);` and what the hell does that mean.

External signal handlers just can not work with thevoid, no need to think that they can. They might in theory, but none had ever messed with it. Please, write code for people, not for some perfectionists idea.

Let's return to ground. I rise following cases:
1. separate thread, please try to eliminate it in favor of IO threads
2. a lot of unneeded code which will always be duplicated - I recommend moving it into `create_server()` and forget that some signals can be handled outside of the thevoid framework
3. this requires example code which will be used as a tutorial/guide for those who needs C++ HTTP server framework. I'm pretty sure your example will have those signal stuff copy-pasted if nothing is changed, and that's a serious red flag about moving that stuff into the framework where is was previously (albeit buggy - handlers invoked by classic signal machinery may not use locks and so on).

This will not take a lot of efforts to complete, and we can move on.

**Comment by shindo** [comment]
1. separate thread looks fine
2. just to refresh your memory - #26
3. OK, I'll try to write some helpful example

**Comment by bioothod** [comment]
Your solution does not look well thought (1), more like a quick and lazy. It still does not provide a way for external application to install full featured signal handler, since there is no way to call functions which are *required* to be called by thevoid's signal handler from external signal handler, even more - it creates a visibility of such possibility which is a path for obscure bugs, so, do not pretend it fixed that issue.
And 3 - Hallelujah.

**Comment by shindo** [comment]
I think that thevoid library should not handle signals at all. That's why I don't want to use IO threads for this task (let them just handle http requests). 

This pull request makes possible to not use proposed signal handling at all (earlier it was not possible, thevoid just handled specific signals). And it's enough to solve the issue. 

I'll try one more time - user is free to create server, register their own handler for SIGTERM signal with signal(), sigaction(), signalfd(), whatever else, and call created server's stop() method.

This way user can handle any signals as they want. But additionally we provide user with convenient methods to register their servers, to specify on which signals we should stop/reload registered servers and to start/stop this library-wide signal handling mechanics.

**Comment by bioothod** [comment]
Of course it is not **that** simple, moreover, what you've written is not true.
If I call `stop()` method from my classic signal handler, I may stuck, since it is not allowed (or maybe allowed, I do not know that). If I catch SIGHUP signal how do I know how to reconfigure server? Even more, what should I call for it, what are the constraints, what will break, deadlock or crash, what are the race conditions?

There is virtually no way *now* for correct client signal handling. That's it.

Your helper class is basically a note 'we will handle all signals ourself, we know how to do it and we will do it without classical signal mess'. It does not help user, for instance, to run over its list of internal tasks and reload config 3 times in a row on SIGALRM receive.

I would understand a set of static helpers like `stop_server()`, `reload_config()` and so on with complete description of how those functions have to be called. I would understand signal helper class which creates additional thread for signal handling (who else in the world does this?), which accepts user's callbacks, again, with full-featured lifetime rules and docs. It could be great if that same logic would be implemented with IO threads.

But this is not the case. What your patch does is a fix for classical signal bugs we had previously (albeit using additional thread) and a way for user to specify which signals thevoid will steal from him.

We are going past each other. Let's concentrate on the last paragraph - you have fixed a bug, that's great, but please think twice about overhead you've introduced, if it is unavoidable (I doubt that), then I will accept pull request (you promised example with detailed description). But it is not a way for users to use their own signal handlers at all.

**Comment by shindo** [comment]
I'll rework this patch (all your comments will be taken into consideration).

**Comment by bioothod** [comment]
That would be great, thank you
